spring.application.name=sedaChimbote
server.port=8083

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:seda
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Mundito
spring.datasource.password=256100

# Mostrar la consola web de H2
spring.h2.console.enabled=true

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect